name: "Pull Image from GCR"
description: "Pulls a Docker image from GCR"
author: "Joshua Thompson"
branding:
  icon: "download-cloud"
  color: "purple"
inputs:
  image:
    description: "Docker image and tag, like 'your_image:latest'"
    required: true
  gcr_location:
    description: "Regional location of the repository, defaults to 'gcr.io'"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
